server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: file:///C:/Users/Kresimir/eclipse-workspace/configrepo
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"